// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/agent_orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Operand1      float64                `protobuf:"fixed64,2,opt,name=operand1,proto3" json:"operand1,omitempty"`
	Operand2      float64                `protobuf:"fixed64,3,opt,name=operand2,proto3" json:"operand2,omitempty"`
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	OperationTime int32                  `protobuf:"varint,5,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"` // для симуляции задержки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_agent_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskRequest) GetOperand1() float64 {
	if x != nil {
		return x.Operand1
	}
	return 0
}

func (x *TaskRequest) GetOperand2() float64 {
	if x != nil {
		return x.Operand2
	}
	return 0
}

func (x *TaskRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *TaskRequest) GetOperationTime() int32 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        float64                `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_agent_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasTask       bool         `protobuf:"varint,1,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`
	Task          *TaskRequest `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskReply) Reset() {
	*x = TaskReply{}
	mi := &file_proto_agent_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReply) ProtoMessage() {}

func (x *TaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReply.ProtoReflect.Descriptor instead.
func (*TaskReply) Descriptor() ([]byte, []int) {
	return file_proto_agent_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *TaskReply) GetHasTask() bool {
	if x != nil {
		return x.HasTask
	}
	return false
}

func (x *TaskReply) GetTask() *TaskRequest {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_proto_agent_orchestrator_proto protoreflect.FileDescriptor

const file_proto_agent_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/agent_orchestrator.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\x98\x01\n" +
	"\vTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\boperand1\x18\x02 \x01(\x01R\boperand1\x12\x1a\n" +
	"\boperand2\x18\x03 \x01(\x01R\boperand2\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\x12%\n" +
	"\x0eoperation_time\x18\x05 \x01(\x05R\roperationTime\"f\n" +
	"\fTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x01R\x06result\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"N\n" +
	"\tTaskReply\x12\x19\n" +
	"\bhas_task\x18\x01 \x01(\bR\ahasTask\x12&\n" +
	"\x04task\x18\x02 \x01(\v2\x12.proto.TaskRequestR\x04task2~\n" +
	"\fOrchestrator\x123\n" +
	"\aGetTask\x12\x16.google.protobuf.Empty\x1a\x10.proto.TaskReply\x129\n" +
	"\n" +
	"SendResult\x12\x13.proto.TaskResponse\x1a\x16.google.protobuf.EmptyB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_agent_orchestrator_proto_rawDescOnce sync.Once
	file_proto_agent_orchestrator_proto_rawDescData []byte
)

func file_proto_agent_orchestrator_proto_rawDescGZIP() []byte {
	file_proto_agent_orchestrator_proto_rawDescOnce.Do(func() {
		file_proto_agent_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_orchestrator_proto_rawDesc), len(file_proto_agent_orchestrator_proto_rawDesc)))
	})
	return file_proto_agent_orchestrator_proto_rawDescData
}

var file_proto_agent_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_agent_orchestrator_proto_goTypes = []any{
	(*TaskRequest)(nil),   // 0: proto.TaskRequest
	(*TaskResponse)(nil),  // 1: proto.TaskResponse
	(*TaskReply)(nil),     // 2: proto.TaskReply
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_proto_agent_orchestrator_proto_depIdxs = []int32{
	0, // 0: proto.TaskReply.task:type_name -> proto.TaskRequest
	3, // 1: proto.Orchestrator.GetTask:input_type -> google.protobuf.Empty
	1, // 2: proto.Orchestrator.SendResult:input_type -> proto.TaskResponse
	2, // 3: proto.Orchestrator.GetTask:output_type -> proto.TaskReply
	3, // 4: proto.Orchestrator.SendResult:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_agent_orchestrator_proto_init() }
func file_proto_agent_orchestrator_proto_init() {
	if File_proto_agent_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_orchestrator_proto_rawDesc), len(file_proto_agent_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_orchestrator_proto_goTypes,
		DependencyIndexes: file_proto_agent_orchestrator_proto_depIdxs,
		MessageInfos:      file_proto_agent_orchestrator_proto_msgTypes,
	}.Build()
	File_proto_agent_orchestrator_proto = out.File
	file_proto_agent_orchestrator_proto_goTypes = nil
	file_proto_agent_orchestrator_proto_depIdxs = nil
}
